name: Package Test

on: workflow_dispatch

jobs:
  package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [
          { node: 18.17.1, electron: 27.0.0, openssl: 1.1.1w }
        ]

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version.node }}
          cache: 'npm'

      - name: Setup (linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:git-core/ppa
          sudo apt-get update
          sudo apt-get install -y git build-essential clang python3 libssl-dev libkrb5-dev libc++-dev
          echo "npm_config_openssl_dir=${{ github.workspace }}/openssl-${{ matrix.version.openssl }}/build" >> "$GITHUB_ENV"

      - name: Build Openssl (linux)
        run: |
          wget -qO- https://www.openssl.org/source/openssl-${{ matrix.version.openssl }}.tar.gz | tar -xz
          cd openssl-${{ matrix.version.openssl }}
          ./config --prefix=${{ github.workspace }}/openssl-${{ matrix.version.openssl }}/build --openssldir=${{ github.workspace }}/openssl-${{ matrix.version.openssl }}/build
          make
          make install

      - name: Install
        env:
          NODEGIT_OPENSSL_STATIC_LINK: 1
        run: npm ci --arch=x64 --runtime=electron --target=${{ matrix.version.electron }} --target_arch=x64 --disturl=https://electronjs.org/headers --build_from_source=true

      - name: Deploy
        run: |
          node lifecycleScripts/clean
          npx node-pre-gyp package --runtime=electron --target=${{ matrix.version.electron }}

      - name: Prepare artifact for upload
        run: |
          touch artifact.tar.gz
          tar -zcf artifact.tar.gz --exclude=artifact.tar.gz .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-package
          path: artifact.tar.gz
          if-no-files-found: error
          retention-days: 5
